version: '3.3'
services:
    springevaluation:
        build: .
        ports:
        - 9090:8080
        depends_on:
        - postgres
    postgres:
        image: postgres
        ports:
        - "5433:5432"
        environment:
        - POSTGRES_PASSWORD=user
        - POSTGRES_USER=user
        - POSTGRES_DB=spring-eval-db
        volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
